<?php

// autoload_namespaces.php generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname(dirname($vendorDir));

return array(
    'MarkdownExtended' => $vendorDir . '/atelierspierrot/markdown-extended/src',
);
