<?php

// autoload_namespaces.php generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'troba' => $vendorDir . '/scandio/troba/lib',
    'Underscore' => $vendorDir . '/anahkiasen/underscore-php/src',
    'Scandio\\lmvc\\modules' => $vendorDir . '/scandio/lmvc-modules/lib',
    'Scandio\\lmvc' => $vendorDir . '/scandio/lmvc/lib',
    'Patchwork' => $vendorDir . '/patchwork/utf8/class',
    'Normalizer' => $vendorDir . '/patchwork/utf8/class',
    'Mustache' => $vendorDir . '/mustache/mustache/src',
    'MarkdownExtended' => $vendorDir . '/atelierspierrot/markdown-extended/src',
    'JSMinPlus' => $vendorDir . '/nitra/php-min/JSMinPlus',
    'Intervention\\Image' => $vendorDir . '/intervention/image/src',
    'Illuminate\\Support' => $vendorDir . '/illuminate/support',
    'CssMin' => $vendorDir . '/nitra/php-min/CssMin',
    'CoffeeScript' => $vendorDir . '/coffeescript/coffeescript/src',
    '' => $baseDir . '/app',
);
